# Generated by Django 4.2 on 2024-07-21 05:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('user_type', models.CharField(max_length=100)),
                ('referenceId', models.IntegerField()),
                ('jwt_token', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('lattitude', models.CharField(default='13.0843', max_length=100)),
                ('longitude', models.CharField(default='80.2705', max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('institution_age', models.IntegerField()),
                ('domain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('location', models.CharField(max_length=500)),
                ('certification', models.BooleanField(default=False)),
                ('no_of_seats', models.IntegerField()),
                ('filled_seats', models.IntegerField(default=0)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('expectations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('current_role', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_amount_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursedetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
