# Generated by Django 4.2 on 2024-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='is_amount_paid',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='tax',
        ),
        migrations.AlterField(
            model_name='payments',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50),
        ),
    ]
