# Generated by Django 4.2 on 2024-07-23 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_payment_timestamp_payments_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='id',
        ),
        migrations.AlterField(
            model_name='coursecenter',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
