# Generated by Django 4.2 on 2024-07-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_payments_id_alter_coursecenter_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_amount_paid',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payments'),
        ),
    ]
