# Generated by Django 4.2 on 2024-08-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=16)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('CourseCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecenter', unique=True)),
            ],
        ),
    ]
