# Generated by Django 4.2 on 2024-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_accountdetails_coursecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='linked_acount_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='product_config_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
