# Generated by Django 4.2 on 2024-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_accountdetails_linked_acount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('linkedIn_profile', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('cv_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('website_link', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
