# Generated by Django 4.2 on 2024-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_facultyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('website_link', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('phone_number', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
