# Generated by Django 4.2 on 2024-08-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_facultyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyrequest',
            name='place',
        ),
    ]
