# Generated by Django 4.2 on 2024-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('currentRole', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
    ]
