# Generated by Django 5.0.6 on 2024-06-04 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0002_coursecenter_student_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecenter',
            name='lattitude',
            field=models.CharField(default='13.0843', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='longitude',
            field=models.CharField(default='80.2705', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecenter',
            name='domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coursecenter',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecenter',
            name='ownerName',
            field=models.CharField(max_length=100),
        ),
    ]
