# Generated by Django 5.0.6 on 2024-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0003_coursecenter_lattitude_coursecenter_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecenter',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='coursecenter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coursecenter',
            name='institutionAge',
        ),
        migrations.RemoveField(
            model_name='coursecenter',
            name='institutionName',
        ),
        migrations.RemoveField(
            model_name='coursecenter',
            name='ownerName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='currentRole',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='email_id',
            field=models.EmailField(default='tt@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='institution_age',
            field=models.IntegerField(default=56),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='institution_name',
            field=models.CharField(default='onnu', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='owner_name',
            field=models.CharField(default='op', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='password',
            field=models.CharField(default='p', max_length=50),
        ),
        migrations.AddField(
            model_name='coursecenter',
            name='phone_number',
            field=models.CharField(default='45', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='current_role',
            field=models.CharField(default='stu', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='tt@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='summa', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='try', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='4352', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='poda', max_length=50),
        ),
    ]
