# Generated by Django 5.0.6 on 2024-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0005_alter_coursecenter_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('institution', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('certification', models.BooleanField(default=False)),
                ('no_of_seats', models.IntegerField()),
                ('description', models.TextField()),
                ('expectations', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
    ]
