# Generated by Django 4.2 on 2024-06-08 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0007_alter_coursedetails_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='expectations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
