# Generated by Django 5.0.6 on 2024-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0009_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('user_type', models.CharField(max_length=100)),
                ('referenceId', models.IntegerField()),
                ('jwt_token', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
