# Generated by Django 5.0.6 on 2024-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static', '0010_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='filled_seats',
            field=models.IntegerField(default=0),
        ),
    ]
